import 'package:flutter/material.dart';

class ProfileTCScreen extends StatefulWidget {
  const ProfileTCScreen({super.key});

  @override
  State<ProfileTCScreen> createState() => _ProfileTCScreenState();
}

class _ProfileTCScreenState extends State<ProfileTCScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xffF2F2F2),
      appBar: AppBar(
        title: const Text(
          "Terms & Conditions",
          style: TextStyle(fontWeight: FontWeight.bold),
        ),
        backgroundColor: Colors.transparent,
        elevation: 0,
        foregroundColor: Colors.black,
      ),
      body: const SingleChildScrollView(
        padding: EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              "1. Acceptance of Terms",
              style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
            ),
            SizedBox(height: 6),
            Text(
              "By accessing or using this app, you agree to be bound by these Terms & Conditions. If you do not agree, please do not use the app.",
              style: TextStyle(fontSize: 14, color: Colors.black87),
            ),
            SizedBox(height: 20),
            Text(
              "2. Purpose of the App",
              style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
            ),
            SizedBox(height: 6),
            Text(
              "This app provides financial and general calculation tools, including but not limited to EMI, Income Tax, SIP, FD, RD, CST, IRR, XIRR, Insurance, and other related calculators. These tools are provided for informational and estimation purposes only.",
              style: TextStyle(fontSize: 14, color: Colors.black87),
            ),
            SizedBox(height: 20),
            Text(
              "3. No Professional Advice",
              style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
            ),
            SizedBox(height: 6),
            Text(
              "The results generated by this app are estimates based on the information entered by users. They do not constitute financial, legal, tax, or professional advice. Users are advised to consult qualified professionals before making financial decisions.",
              style: TextStyle(fontSize: 14, color: Colors.black87),
            ),
            SizedBox(height: 20),
            Text(
              "4. Accuracy of Information",
              style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
            ),
            SizedBox(height: 6),
            Text(
              "We strive to provide accurate calculations; however, we do not guarantee the completeness, reliability, or accuracy of the results. The app owner is not responsible for any errors, omissions, or outcomes resulting from the use of this app.",
              style: TextStyle(fontSize: 14, color: Colors.black87),
            ),
            SizedBox(height: 20),
            Text(
              "5. User Responsibility",
              style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
            ),
            SizedBox(height: 6),
            Text(
              "Users are solely responsible for the data they enter and the decisions made based on the calculation results. The app is not liable for any financial loss, damage, or consequences arising from its use.",
              style: TextStyle(fontSize: 14, color: Colors.black87),
            ),
            SizedBox(height: 30),
          ],
        ),
      ),
    );
  }
}
